kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: echoapi
spec:
  triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - echoapi
        from:
          kind: ImageStreamTag
          name: 'echoapi:latest'